COMPONENT=PacketAppConfigC
CFLAGS+=-DCC2420_DEF_RFPOWER=31 -DCC2420_DEF_CHANNEL=26

CFLAGS += -I$(TOSDIR)/lib/net \
          -I$(TOSDIR)/lib/net/le \
          -I$(TOSDIR)/lib/net/bcp
include $(MAKERULES)
